language: python
sudo: false

python:
  - 3.5
  - &mainstream_python 3.6

env:
  global:
    - FLIT_USERNAME=andrew.svetlov
    - secure: "qufbAtfhtnq5IN1H8CbSEStMqE24EjSQnIGFPXiMUJsWJ6vwMt8PCs/MfuplZMuUeozeV1fjSOTCqFRDGUeM4Lf5kMkdDiZM+x3GTnPK0sPd2MqbfcTXFeiXu7muQxY+Xcm9B1r9IOHwUTL2i93NstckDA/Lmg0/6NyWTZztt86+Ioht9tD+b2lsky4pL1yHQFlij3bBjOGK3NH3ZMCiqxMN1rBeYuP8rBlgNUAhf2uZjmviqWjbpk86YPD6XrIH6V6d5PuETuTfFI+J4wjsuXUImp8d+auEsYQPV6/YDXhRJCU3NU6p0uAYi68Gc4Pwp1UEtePOJ7t336y2LS5hTWm9OCql7G1wokMOu4LmvsGI7Wfn+R6UwW9EMFtinvkxBqyRJeRohtgU+B8zE6usOwSkk4gggPr+qmm64jmypu3lbDNCnX5reGXfRDBojUiXtnJ5Wo/UWekjJrV57xOnkpIv/hWL0TJ61r/diS0tXgsMJTspO7Pds5PmsX/DE35ZvPFceN5AifUmQVDs2S2JmBWkpcryXwnz0Os2KvsH57v/Eog3tJVzc7JMU+QWWyVK/ZDK9pyOUonwMX/AmdXXj+gMyeMR+IwLfzyx3jZhd0vipTB4zS981siJd+xKrr6oKLYeEb/ptWYcDWHLeFjpL15gjGfZI0/ILMdwxfaEtqU="


install:
  - travis_retry pip install codecov
  - travis_retry pip install -r requirements/ci.txt
  - flit install --symlink
script:
  - make test
  - codecov

_helpers:
- &_mainstream_python_base
  python: *mainstream_python
- &_reset_steps
  env: []
  before_install: skip
  install: skip
  script: skip
  after_success: []

jobs:
  include:
  - stage: lint
    <<: *_mainstream_python_base
    <<: *_reset_steps
    install:
      - travis_retry pip install -r requirements/lint.txt
      - flit install --symlink
    script:
      - make flake
  - stage: deploy
    if: tag IS present
    <<: *_mainstream_python_base
    <<: *_reset_steps
    install:
      - travis_retry pip install -r requirements/ci.txt
    script:
      - flit publish

stages:
  - name: lint
  - name: test
  - name: deploy
    # This will prevent deploy unless it's a tagged commit:
    if: tag IS present

cache: pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
